base/base_inner.ts

/cc @zeke 
Didn't push this before transferring 😆

Fix the implementation of Electron.Event

---

lib/module-declaration.js

Setup for static properties (touchbar)

---

README.md
base/base_header.ts
package.json

rename the project

---

README.md

Missed some things on the first go around.
#13

rename more things

---

lib/module-declaration.js
lib/utils.js
vendor/fetch-docs.js

/cc @zeke @felixrieseberg @kevinsawicki

Prefix things correctly in the process module

---

package.json
test-smoke/electron/test/main.ts
vendor/fetch-docs.js

Update to latest master of electron/electron

---

test-smoke/electron/test/main.ts
vendor/fetch-docs.js

hidden-inset -> hiddenInset

---

.travis.yml
package.json

Don't do the tests and stuff multiple times on CI, it takes AGGEESSS

---

base/base_footer.ts
index.js
lib/master-interfaces.js
test-smoke/electron/test/main.ts
test/output_spec.js
tslint.json

and added const declarations so that `app` etc are accessible.
Fully backwards compatible. I also added a couple of lines to the main.ts to test the changes.
Fixes #55
Also fixes #33 because it was bugging me.

Changed `declare module "electron"` to export = Electron

---

test-smoke/electron/test/main.ts

See: https://github.com/electron/electron/pull/10936

Added required content parameter to displayBalloon

---

test-smoke/electron/test/main.ts

This will need to be forcefully merged and published manually because the tests won't pass until https://github.com/electron/electron/pull/11925 is merged and that PR won't be merged until this is released 👍

Update autoUpdater smoke tests for new API

---

test-smoke/electron/test/main.ts
vendor/fetch-docs.js

Required for Electron 2.0 API change in https://github.com/electron/electron/pull/11968

sync menu.popup signature to breaking change in Electron 2.0

---

package-lock.json
package.json

This can help us avoid linting gotchas like the one in #90

update standard and use its fix flag

---

test-smoke/electron/test/main.ts
vendor/fetch-docs.js

For reference, see https://github.com/electron/electron/pull/12362.

fix: `position` is dead, long live `before/after`

---

test-smoke/electron/test/main.ts
vendor/fetch-docs.js

Reverts electron/electron-typescript-definitions#119

Revert "fix: update zoom fns for sync"

---

test-smoke/electron/test/main.ts
vendor/fetch-docs.js

BREAKING CHANGE: update zoom fns for sync versions

fix: update zoom fns for sync

---

.travis.yml

We are the only consumers, we should only really care about latest stable node

build: only run on node 10

---

base/base_inner.ts
lib/module-declaration.js
package-lock.json
package.json
vendor/fetch-docs.js

BREAKING CHANGE
In tandem with https://github.com/electron/electron/pull/16954.
cc @MarshallOfSound

refactor: remove Event interface from hardcoded types

---

src/utils.ts

feat: support Partial<T> style types

---

src/dynamic-param-interfaces.ts
src/module-declaration.ts
src/utils.ts
yarn.lock

Depends on https://github.com/electron/docs-parser/pull/10

fix: handle an method parameter being an enum type with one part of enum being a dynamic struct

---

src/module-declaration.ts

As in title, redefine all events in parent classes in the child class so that declaration merging works

fix: merge events with parent classes so that class type merging for event emitters works

---

.circleci/config.yml
.husky/pre-commit
package.json
yarn.lock

As in title, no user facing changes

build: update deps to clean up yarn audit

---

src/primary-interfaces.ts

fix: export the WebviewTag type

---

src/utils.ts

fix: WebFrame is not an eventemitter module

---

src/utils.ts

4 year old code, can't explain why we need it, it breaks things, let's delete it

fix: do not prefix promise inner types

---

base/base_footer.ts

fix: ensure original-fs is exported correctly

---

src/utils.ts

fix: bad indenting for multi-line-breaks

---

src/module-declaration.ts

https://nodejs.org/api/events.html#emitteraddlistenereventname-listener
https://nodejs.org/api/events.html#emitteroffeventname-listener

fix: support for `off()` & `addListener()` `EventEmitter` aliases

---

src/module-declaration.ts

I think this was a debug statement that snuck in via #259.

fix: remove rogue console.log
