base/base_inner.ts, lib/module-declaration.js, tslint.json
The public prefix is not necessary and almost no definitions on DefinitelyTyped use them.
=> Remove public prefix + disable "member-access" tslint rule

cli.js
This PR moves the responsibility of linting the `electron.d.ts` file into the module itself, so `electron/electron` will have fewer moving typescript parts.
The CLI now programmatically runs `tslint` on the generated output. If there are no errors, the file is written and the process exits with 0. If there are errors, they are printed and the process exits with 1.
cc @MarshallOfSound @kevinsawicki
=> tslint output before creating file

cli.js
This will stop issues happening again with generated types
/cc @zeke
=> Run tsc on the output at gen time

.npmignore
Followup to #41 (v1.2.1) which adds some `tsc` checks that work in development but are not working in the published npm package.
I think the reason for this is that the `/test-smoke/electron/test` directory is being npmignored by the pattern `test`.
=> do not npmignore tests

package.json
A partial fix for https://github.com/electron/electron-typescript-definitions/issues/43
This will enable electron/electron to run `tsc` checks on the generated `electron.d.ts` file.
=> move @types/node to dependencies

cli.js, lib/module-declaration.js, lib/utils.js
Fixes #48 
/cc @felixrieseberg You made the original change before to default this to true for everything, it appears to was purely to fix all the constructor object properties needing to be optional by default so I think this still covers that case
=> Change default optional value for methods and events

lib/module-declaration.js, lib/utils.js, test/utils_spec.js
* Don't check description in utils.isOptional. It was incorrectly identifying the parameter to `BrowserView.setBackgroundColor` as optional. This is no longer needed since `electron-docs-linter` marks non-optional things as `required`.
* Assume methods are non-optional for now. This makes e.g. `app.commandLine.appendSwitch` non-optional and does not result in false positives.
=> Fix utils.isOptional()

lib/module-declaration.js, vendor/fetch-docs.js
The `process` module is a special case because it's part of the NodeJS namespace. As such, the `Electron.` prefix must be used to refer to anything outside the NodeJS process namespace.
This PR updates that special case scenario to account for `process` methods that return custom types, such as `CPUUsage` and `IOCounters`.
Fixes https://github.com/electron/electron/pull/9599
=> support returning custom types

cli.js, lib/module-declaration.js, vendor/fetch-docs.js
Fixes #60 
This PR wraps key names like `2d_canvs` in quotes to prevent TS compiler errors. It also updates the CLI to produce more readable error output.
=> Wrap numeric keys in quotes

base/base_inner.ts
According to: https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/atom/browser/api/event_emitter.cc#L71
Helps for https://github.com/electron/electron/issues/10448
=> Event definition is wrong (fixes #73)

lib/module-declaration.js
WebviewTag adds electron-specific overloads to addEventListener and removeEventListener when it extends HTMLElement. However, it does not include the original overloads from HTMLElement, and Typescript does not include them when WebviewTag extends HTMLElement. This change adds those previously-missed overloads to WebviewTag. It is necessary to allow users of electron.d.ts to compile with Typescript 2.6 --strict.
Fixes #79
=> Add add/removeEventListener overloads from HTMLElement

lib/utils.js
This just adds a helper to make it easier to add `TouchBarItem` as a type in the TB docs
=> Add support for abstract TouchBarItem

.gitignore, .npmignore
semantic-release noticed that we were not gitignoring `.npmrc`:
```
> electron-typescript-definitions@1.3.0 prepack .
> check-for-leaks
warning: .npmrc is not in your .gitignore file
warning: .npmrc is not in your .npmignore file
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-typescript-definitions@1.3.0 prepack: `check-for-leaks`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-typescript-definitions@1.3.0 prepack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-02-12T19_15_06_376Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-typescript-definitions@0.0.0-development semantic-release: …
```
=> fix: avoid leaking secrets

test-smoke/electron/test/renderer.ts
In coordination with the imminent release of `3.0.0`, remove deprecated reference to `webFrame.registerURLSchemeAsSecure('app')`.
Fixes TS definitions error in https://github.com/electron/electron/pull/13050.
/cc @MarshallOfSound @electron/electrocats
=> remove reference to webFrame.registerURLSchemeAsSecure

lib/module-declaration.js, package-lock.json, vendor/fetch-docs.js
Required for: https://github.com/electron/electron/pull/13542
=> fix: allow primitives in NodeJS.Process modifications

lib/utils.js
The [StreamProtocolResponse.data](https://github.com/electron/electron/blob/master/docs/api/structures/stream-protocol-response.md) property is supposed to be a **Node.js** readable stream.
Unfortunately the `ReadableStream` type is ambiguous between the Node.js `ReadableStream` and the `ReadableStream` interface defined in the [web Streams standard](https://streams.spec.whatwg.org/#rs-class) and since the web stream standard is part of the standard lib in TS it'll choose that.
This PR special cases the `ReadableStream` type name to qualify it with the Node.js namespace.
I wasn't sure what the best approach here would be, special case it in the definition generator or update the documentation to be explicit about the type.
I'm happy to drop this and PR a change to the docs if you'd like. …
=> fix: Special case ReadableStream type to mean Node.js ReadableStream

test-smoke/electron/test/main.ts, vendor/fetch-docs.js
Reverts electron/electron-typescript-definitions#108
=> chore: Revert "fix: `position` is dead, long live `before/after`"

test-smoke/electron/test/main.ts, vendor/fetch-docs.js
Reverts electron/electron-typescript-definitions#110
=> fix: Revert "fix: `position` is dead, long live `before/after`"

lib/module-declaration.js, lib/utils.js, vendor/fetch-docs.js
Fixes generation for https://github.com/electron/electron/pull/14456
=> fix: handle top level primitives in the process module

test-smoke/electron/test/renderer.ts, vendor/fetch-docs.js
Updates the spellcheck API in smoke tests.
[Corresponding electron change https://github.com/electron/electron/pull/14032]
=> fix: Update spellcheck API in smoketest

test-smoke/electron/test/main.ts, vendor/fetch-docs.js
Fixes lint failures in https://github.com/electron/electron/pull/16410.
Update zoom-related `MenuItems` to be synchronous.
cc @MarshallOfSound @ckerr @deepak1556
=> fix: update zoom fns for sync

test-smoke/electron/test/main.ts, vendor/fetch-docs.js
Point e-t-d to https://github.com/electron/electron/pull/16464 to pick up the new promise versions of our Cookie CRUD API
CC @codebytere, @MarshallOfSound
=> chore: bump ELECTRON_COMMIT for cookie promises api

lib/module-declaration.js, lib/utils.js
Thanks to @MarshallOfSound.
This PR fixes https://github.com/electron/electron/pull/16593#issuecomment-458734535.
=> fix: Add builtins check for return type

test-smoke/electron/test/main.ts, test-smoke/electron/test/renderer.ts, vendor/fetch-docs.js
This PR updates the tests to use the new schemes changes that have landed in electron.
=> fix: Update tests for new schemes api

lib/utils.js, test/utils_spec.js
Account for situations like inherited `GlobalEvent` which has a type `preventDefault` of type `() => void`
cc @MarshallOfSound
=> feat: add new known VoidFunction type

base/base_inner.ts
This will fix an issue with matching `EventEmitter` in Electron's code to this definition
cc @felixrieseberg @codebytere
=> fix: update eventNames API signature to match node

lib/utils.js, package-lock.json, package.json
Blocked pending: https://github.com/electron/electron-docs-linter/pull/112
Add support for `Record<A, B>` in our documentation as types to represent generic objects better.  I.e. `Record<string, string>` maps to an object with string keys and string values.
=> feat: add support for Record<A, B>

lib/utils.js
The `crashReporter` API is not an EventEmitter
=> fix: crashreporter is not an EventEmitter

cli.js, lib/utils.js, package.json, vendor/fetch-docs.js
Required for https://github.com/electron/electron/pull/16593
`Promise<ElectronType>` becomes `Promise<Electron.ElectronType>`
=> fix: prefix inner types for safety

src/utils.ts
Closes https://github.com/electron/electron/issues/13520.
Ensure that all classes and modules which are _not_ EventEmitters are not incorrectly typed as such. Updated by looking at the `electron.d.ts` file, seeing which modules/classes were typed as extending `NodeJS.EventEmitter` but didn't emit anything, and adding the delta.
cc @MarshallOfSound
=> fix: overzealous EventEmitter typings

package.json, src/dynamic-param-interfaces.ts, src/index.ts, src/module-declaration.ts, src/utils.ts, yarn.lock
This does a few things:
* makes `readonly` work
* puts `@deprecated` in our defs for deprecated APIs
* puts `@experimental` in our defs for experimental APIs
* puts `@platform ...` in our defs for APIs that only work on certain platforms
=> feat: expose deprecated,readonly and platform annotations in the ts defs

base/base_inner.ts, src/module-declaration.ts
Fixes https://github.com/electron/electron/issues/21612
In the latest `@types/node`, `NodeJS.EventEmitter` was changed from class to interface. But some classes in `electron.d.ts` extend it (class cannot extend interface) so it causes a compilation error as I reported in above issue. This issue is not immediate because Electron's Node.js version is still v12. But fixing this issue is also valid for `@types/node@12`.
This patch fixes the issue with advice from @andrewbranch.
I confirmed above issue was resolved by `electron.d.ts` generated by this pull request branch (I had generated `electron-api.json` in the latest branch of electron repository).
=> Fix compilation error with the latest @types/node

src/master-interfaces.ts
Adds a class required for electron/electron#25464 to import `webFrameMain`.
=> feat: classify webFrameMain

src/utils.ts
For a union type of a param where one part of the union is an Object type, we must retain the name of the object param so that typify has context on what to define the interface as.
=> fix: pass param name to object typify

README.md
Was still pointing at Travis CI, instead of CircleCI
=> docs: update status badge

base/base_header.ts, src/utils.ts
net.fetch() needs to reference the Response object in Node.js. There's already
some object called 'Response' in the Electron namespace, and there's [no way to
escape a scope](https://github.com/Microsoft/TypeScript/issues/983) in
typescript, so here we go.
=> feat: expose GlobalResponse for net.fetch

CONTRIBUTING.md, README.md, base/base_header.ts, package.json
There were a few lingering references to `electron-typescript-definitions` as the repo name. Also added a status badge for the package because I like those.
=> chore: update references to previous repo name

base/base_header.ts, base/base_inner.ts, package.json, src/dynamic-param-interfaces.ts, src/module-declaration.ts, src/utils.ts, yarn.lock
This adds support for the new event type blocks that https://github.com/electron/docs-parser/pull/80 generates. Specifically...
<details>
```json
{
"name": "event",
"description": "",
"collection": false,
"type": "Event",
"eventProperties": [
{
"name": "url",
"description": "The URL the frame is navigating to.",
"required": true,
"additionalTags": [],
"collection": false,
"type": "String",
"possibleValues": null
},
{
"name": "isSameDocument",
"description": "Whether the navigation happened without changing document. Examples of same document navigations are reference fragment navigations, pushState/replaceState, and same page history navigation.",
"required": true,
"additionalTags": [],
"collection": false,
"type": "boolean"
},
{
"name": "isMainFrame",
"description": "True if the …
```
=> feat: add new Event support for extensible params

src/primary-interfaces.ts
`import { Event } from 'electron';` should still import the `Event` type
=> fix: ensure Event is exported still

base/base_footer.ts
`require` `original-fs` with `node:` protocol works in electron. Add `node:original-fs` like `node:fs`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6a06fb27adf8992c0b345dea508a6ec118f6cdb0/types/node/fs.d.ts#L4041-L4043
=> fix: add `node:original-fs`

src/utils.ts
As in title, a better version of https://github.com/electron/typescript-definitions/pull/227 as that logic is still needed
=> fix: prefix promise types where appropriate

src/module-declaration.ts
Fixes https://github.com/electron/electron/issues/39790
=> fix: spread sub type onto parent type for dynamic param interface

src/dynamic-param-interfaces.ts, src/index.ts
This PR does two things to ensure type deduplication:
* Constructor types are declared _first_ so their is a baseline for setters/getters to be compared too
* Type dedupe logic now ignores descriptions so that the wording doesn't have to be identical in the docs
=> fix: ensure that identical types in set/get are deduper from ctor

base/base_footer.ts, package.json, src/primary-interfaces.ts, yarn.lock
This adds a `'electron/utility'` module for modules available to the utility process.
This PR depends on https://github.com/electron/docs-parser/pull/95 in order to add the `ProcessBlock.utility` property.
Opting to make the change in a minimal way to not interfere with the main+renderer=common logic and just add the additional `Utility` with just the minimal set of exports available to the utility process.
See https://github.com/electron/electron/pull/40017 for an example of adding new API to the utility process that will need this change.
=> feat: add electron/utility module for utility process

src/module-declaration.ts, src/primary-interfaces.ts
The remote module is now using its own https://github.com/electron/remote/blob/main/index.d.ts
=> chore: remove obsolete support for the remote module

src/primary-interfaces.ts
Added in #246, the Utility namespace currently has no concrete values in it on electron/electron@main. This change ensures Electron.Utility is available as a property even when the namespace has no values.
Takes advantage of declaration merging: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
Other approaches considered:
- Separating out the values from each namespace into interfaces and setting properties for each interface.
- Decided this was too invasive for questionable value
- Adding a dummy value to the Utility namespace to ensure it's never empty.
- Decided too much of a hack and dummy value would be visible to end users
Tested with `node spec/ts-smoke/runner.js` on electron/electron@main
Should unblock https://github.com/electron/electron/pull/40264 to …
=> fix: ensure Electron.Utility property exists

src/module-declaration.ts, test/utils_spec.js
Regarding the comment for the event declaration, it seems that the `@deprecated` tag description does not follow JSDoc rules because it is written for multiple methods at once.
https://jsdoc.app/tags-deprecated.html
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#deprecated
https://github.com/typescript-eslint/typescript-eslint/issues/1223
With the current output format, some methods are not detected by ESLint ([eslint-plugin-deprecation](https://github.com/gund/eslint-plugin-deprecation)) error checking, so it may be difficult to notice when an event you are using is deprecated.
I think it would be better to be able to emit the `@deprecated` tag for each method so that ESLint can check all usage of deprecated events.
**Before correction:**
```TSX
/**
* Emitted …
```
=> fix: event declaration additional tags

src/bin.ts
```diff
- ✔ Electron Typescript Definitions generated in "/Users/erick.zhao/Developer/electron/src/electron" took 170ms
+ ✔ Electron Typescript Definitions generated in "/Users/erick.zhao/Developer/electron/src/electron/electron.d.ts" took 170ms
````
This is a nicer output for the CLI :)
=> fix: print full file path in CLI

src/module-declaration.ts, src/utils.ts, test/utils_spec.js
Instead of hard-coding a list of modules, we now infer if a module/class is an eventemitter with the following heuristic:
* If the module / class has any events it's an emitter
* If the module / class exposes `on`, `once` and `removeListener` it's an emitter (e.g. `ipcMain`)
This correctly identifies several exposed interfaces as not being emitters and improves the type safety of newly added modules
=> fix: infer EventEmitter extensions from API

package.json
https://github.com/mochajs/mocha/blob/5f96d511dbf913f135b92198aab721a27f6b44fe/package.json#L47C14-L47C23
Minimum for our mocha runner. All tests pass on this version.
=> chore: add  `engines.node` to package.json

src/module-declaration.ts
This seems to have been an oversight from the original implementation, having zero parameters is valid and `() => void` is way better than `Function`.
`Function` is effectively `any` when it comes to calling / binding and such
=> fix: emit listeners with no params explicitly

src/utils.ts, test/utils.spec.ts
I'm considering making some of the IPC types support generics for https://github.com/electron/rfcs/pull/8. While experimenting, I noticed we don't generate them for custom types.
=> feat: allow custom types with inner types

base/base_footer.ts
`File.path` has been removed since Electron v32 but the type still remains.
Removing solely `File.path` would result in empty interface `File`; removing the whole inferface sounds better.
https://www.electronjs.org/docs/latest/breaking-changes#removed-filepath
https://github.com/electron/electron/pull/42053
=> fix: remove `File.path`

src/utils.ts
Was trying to type `Promise<null>` and found it resolved to `Promise<Electron.null>`
=> fix: add null to primitives

src/primary-interfaces.ts
As part of electron/rfcs#14 we're adding a new utilityProcess-only module to `electron/utility`, but it turns out we weren't properly handling that case here.
=> fix: include utilityProcess-only modules in electron/utility

src/utils.ts, test/utils.spec.ts
The return type of `Promise<undefined>` actually comes up a decent amount in Web spec typings, so let's ensure we can support that typing for better alignment.
=> fix: don't prefix undefined since it's a primitive
